### ISSUE TITLE
is there any other ontology alignment framework?

### ISSUE THREAD

**Issue by HamedBabaei** [sciknoworg/OntoAligner#12]
Two list: 

- Ontology Matching/Alignment libraries
1. https://github.com/KRR-Oxford/DeepOnto 
2. https://github.com/allenai/ontoemma (no longer maintained!)
3. https://github.com/okgreece/Alignment 
4. https://github.com/IBM/ontology-alignment 

- Ontology

**Comment by YucelClk** [comment]
6. [https://github.com/AgreementMakerLight/AML-Project](https://github.com/AgreementMakerLight/AML-Project)
8. [https://github.com/ernestojimenezruiz/logmap-matcher](https://github.com/ernestojimenezruiz/logmap-matcher)
